# Generated by Django 3.2.3 on 2021-05-19 13:30

from django.db import migrations

def create_data(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Job(title="Entry-Level Java Developer in New Jersey", contactPhone="111-222-3333", contactEmail="thisguyhasmail@gmail.com", description="Looking for a Java developer in the North New Jersey area. No professional experience required, but applicants must pass multiple screenings.", posterName="HR dude").save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(create_data),
    ]
